FROM rappdw/docker-java-python:openjdk1.8.0_171-python3.6.6


ADD server server
WORKDIR /server
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 5000



CMD ["python", "server.py"]






